In [5]:
import import_ipynb            #for import ipynb files
import mylibrary_true as ml         #importing library
import numpy as np             #for loading file
import math                    #floor and ceil

In [6]:
#Loading the files

A = np.loadtxt('q2.csv', delimiter = ',')  
B = ml.Matrix_operations.generate_identity(4)   #generating an identity matrix B
print(A)
print(B)

[[0. 0. 0. 2.]
 [0. 0. 3. 0.]
 [0. 4. 0. 0.]
 [5. 0. 0. 0.]]
[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


In [7]:
#augmenting the matrices A and B, keeping one for comparison(original)

aug_mat_original = ml.Matrix_operations.augment_matrix(A, B)    
aug_mat = ml.Matrix_operations.augment_matrix(A, B)



#Printing the initial augmented matrix

print("The original augmented matrix is:", "\n")
ml.Printing.print_matrix(aug_mat_original)



#Performing Gauss Jordan Elimination to find out the inverse of A

ml.Gauss_jordan.solve(aug_mat)

#Printing the final augmented matrix after elimination #Abha Vishwakarma 1911003

print("The final augmented after gauss jordan elimination matrix is:", "\n")
ml.Printing.print_matrix(aug_mat)



#seperating the augmented matrix into its components

aug_A, inv_A = ml.Matrix_operations.separate_aug_mat(aug_mat)


#Printing the inverse matrix

print("The inverse matrix is:")
ml.Printing.print_matrix(inv_A)



#Mutiplying A with its inverse and printing to check if the inverse is correct

mult = ml.Round.round_matrix(ml.Matrix_operations.mat_mult(A, inv_A), 2)

print("Matrix multiplication of A and A inverse is:")
ml.Printing.print_matrix(mult)

'''If multiplication of A and A inverse is close to zero then A inverse is correct to two orders of magnitude'''



The original augmented matrix is: 

[0. 0. 0. 2. 1. 0. 0. 0.]
[0. 0. 3. 0. 0. 1. 0. 0.]
[0. 4. 0. 0. 0. 0. 1. 0.]
[5. 0. 0. 0. 0. 0. 0. 1.]


The final augmented after gauss jordan elimination matrix is: 

[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.25, 0.0]
[0.0, 0.0, 1.0, 0.0, 0.0, 0.33, 0.0, 0.0]
[0.0, 0.0, 0.0, 1.0, 0.5, 0.0, 0.0, 0.0]


The inverse matrix is:
[0.0, 0.0, 0.0, 0.2]
[0.0, 0.0, 0.25, 0.0]
[0.0, 0.33, 0.0, 0.0]
[0.5, 0.0, 0.0, 0.0]


Matrix multiplication of A and A inverse is:
[1.0, 0.0, 0.0, 0.0]
[0.0, 0.99, 0.0, 0.0]
[0.0, 0.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 1.0]




'If multiplication of A and A inverse is close to zero then A inverse is correct to two orders of magnitude'