In [21]:
import import_ipynb            #for import ipynb files
import mylibrary_true as ml         #importing library
import numpy as np             #for loading file
import math                    #floor and ceil

In [22]:
#Loading files

A = np.loadtxt('q3_1.csv', delimiter = ',')
b = np.loadtxt('q3_2.csv', delimiter = ',')
b = ml.Matrix_operations.make_proper_column(b)        #Making b of the form [[],[],[],...]
print(A)
print(b)

[[ 3. -7. -2.  2.]
 [-3.  5.  1.  0.]
 [ 6. -4.  0. -5.]
 [-9.  5. -5. 12.]]
[[-9.0], [5.0], [7.0], [11.0]]


In [23]:
#Printing the equation

ml.Printing.print_eq(A,b)

The given equations are:


3.0 x +  -7.0 y +  -2.0 z +  2.0 w =  -9.0
-3.0 x +  5.0 y +  1.0 z +  0.0 w =  5.0
6.0 x +  -4.0 y +  0.0 z +  -5.0 w =  7.0
-9.0 x +  5.0 y +  -5.0 z +  12.0 w =  11.0




In [24]:
#Solving using dolittle

x = ml.LU.solve_dolittle(A, b)


#Printing the solutions #Abha Vishwakarma 1911003

print("Upon using dolittle decomposition for Ax = b")
ml.Printing.print_sol(ml.Round.round_matrix(x))

Upon using dolittle decomposition for Ax = b
The solutions are:


x  =  3.0
y  =  4.0
z  =  -6.0
w  =  -1.0




In [25]:
#checking the solutions

chk = ml.Matrix_operations.mat_mult(A, x)
print("Upon taking the product A*x we get:")
print(chk)

'''This matrix is equal to the b matrix given, hence the solutions are correct to the desired order'''

Upon taking the product A*x we get:
[[-9.0], [5.0], [7.0], [11.0]]


'This matrix is equal to the b matrix given, hence the solutions are correct to the desired order'